const QRCode = require('qrcode');
const fs = require('fs');

const url = process.argv[2];
if (!url) {
  console.error('Usage: node generate-sheet.js <URL>');
  process.exit(1);
}

const sudokuPuzzle = [
  ".8.....9.",
  ".7..6.21.",
  "..6.487..",
  "8.....53.",
  ".2.......",
  "163......",
  "...4.19..",
  ".......7.",
  "2.97....5"
];

const getSudokuPart = (index) => {
  const rowOffset = Math.floor((index - 1) / 3) * 3;
  const colOffset = ((index - 1) % 3) * 3;
  let part = '';
  for (let i = 0; i < 3; i++) {
    part += sudokuPuzzle[rowOffset + i].slice(colOffset, colOffset + 3);
  }
  return part;
};

const generateQrCodes = async () => {
  const qrCodes = [];
  for (let i = 1; i <= 9; i++) {
    let qrUrl;
    if (i === 5) {
      qrUrl = `${url}?n=${i}&fillerfill`;
    } else {
      const sudokuPart = getSudokuPart(i);
      qrUrl = `${url}/part.html?n=${i}&s=${sudokuPart}`;
    }
    const qrDataUrl = await QRCode.toDataURL(qrUrl, {
      errorCorrectionLevel: 'H',
      width: 512,
      margin: 2,
    });
    qrCodes.push(qrDataUrl);
  }
  return qrCodes;
};

const createHtml = (qrCodes) => {
  const qrCodeImages = qrCodes.map(qr => `<img src="${qr}" alt="QR Code">`).join('');

  let sudokuTable = '<table class="sudoku-grid">';
  for (let i = 0; i < 9; i++) {
    sudokuTable += '<tr>';
    for (let j = 0; j < 9; j++) {
      const char = '.';
      // const char = sudokuPuzzle[i][j];
      let classes = [];
      if ((i + 1) % 3 === 0 && i < 8) {
        classes.push('row-separator');
      }
      if ((j + 1) % 3 === 0 && j < 8) {
        classes.push('col-separator');
      }
      sudokuTable += `<td class="${classes.join(' ')}">${char === '.' ? '' : char}</td>`;
    }
    sudokuTable += '</tr>';
  }
  sudokuTable += '</table>';

  return `
<!DOCTYPE html>
<html lang="en">
<!-- THIS FILE IS GENERATED BY generate-sheet.js -->
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QR Code Sheet</title>
  <style>
    body {
      font-family: sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .qr-grid-container {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      grid-gap: 140px;
      width: 1000px;
    }
    img {
      width: 100%;
      height: auto;
    }
    .sudoku-grid {
      border-collapse: collapse;
      margin-bottom: 80px;
      border: 3px solid black;
    }
    .sudoku-grid td {
      width: 70px;
      height: 70px;
      border: 1px solid black;
      text-align: center;
      font-size: 30px;
    }
    .sudoku-grid .row-separator {
      border-bottom: 3px solid black;
    }
    .sudoku-grid .col-separator {
      border-right: 3px solid black;
    }
  </style>
</head>
<body>
  <p>Das mittlere Feld hat die Lösung...</p>
  ${sudokuTable}
  <div class="qr-grid-container">
    ${qrCodeImages}
  </div>
</body>
</html>
  `;
};

generateQrCodes()
  .then(qrCodes => {
    const html = createHtml(qrCodes);
    fs.writeFileSync('sheet.html', html);
    console.log('sheet.html generated successfully.');
  })
  .catch(err => {
    console.error('Error generating QR codes:', err);
  });
