const QRCode = require('qrcode');
const fs = require('fs');

const url = process.argv[2];
if (!url) {
  console.error('Usage: node generate-sheet.js <URL>');
  process.exit(1);
}

const generateQrCodes = async () => {
  const qrCodes = [];
  for (let i = 1; i <= 9; i++) {
    const qrUrl = `${url}?n=${i}`;
    const qrDataUrl = await QRCode.toDataURL(qrUrl, {
      errorCorrectionLevel: 'H',
      width: 512,
      margin: 2,
    });
    qrCodes.push(qrDataUrl);
  }
  return qrCodes;
};

const createHtml = (qrCodes) => {
  const qrCodeImages = qrCodes.map(qr => `<img src="${qr}" alt="QR Code">`).join('');

  const sudokuPuzzle = [
    "58.1....7",
    "...5....26",
    "....1...4",
    "1........",
    "..42.....",
    "......6.8",
    "7.1..3...",
    "..54..9..",
    "........."
  ].map(row => row.replace(/ /g, ''));

  let sudokuTable = '<table class="sudoku-grid">';
  for (let i = 0; i < 9; i++) {
    sudokuTable += '<tr>';
    for (let j = 0; j < 9; j++) {
      const char = sudokuPuzzle[i][j];
      let classes = [];
      if ((i + 1) % 3 === 0 && i < 8) {
        classes.push('row-separator');
      }
      if ((j + 1) % 3 === 0 && j < 8) {
        classes.push('col-separator');
      }
      sudokuTable += `<td class="${classes.join(' ')}">${char === '.' ? '' : char}</td>`;
    }
    sudokuTable += '</tr>';
  }
  sudokuTable += '</table>';

  return `
<!DOCTYPE html>
<html lang="en">
<!-- THIS FILE IS GENERATED BY generate-sheet.js -->
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QR Code Sheet</title>
  <style>
    body {
      font-family: sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .qr-grid-container {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      grid-gap: 140px;
      width: 1000px;
    }
    img {
      width: 100%;
      height: auto;
    }
    .sudoku-grid {
      border-collapse: collapse;
      margin-top: 80px;
      border: 3px solid black;
    }
    .sudoku-grid td {
      width: 70px;
      height: 70px;
      border: 1px solid black;
      text-align: center;
      font-size: 30px;
    }
    .sudoku-grid .row-separator {
      border-bottom: 3px solid black;
    }
    .sudoku-grid .col-separator {
      border-right: 3px solid black;
    }
  </style>
</head>
<body>
  <div class="qr-grid-container">
    ${qrCodeImages}
  </div>
  ${sudokuTable}
  <p>Das mittlere Feld hat die Lösung...</p>
</body>
</html>
  `;
};

generateQrCodes()
  .then(qrCodes => {
    const html = createHtml(qrCodes);
    fs.writeFileSync('sheet.html', html);
    console.log('sheet.html generated successfully.');
  })
  .catch(err => {
    console.error('Error generating QR codes:', err);
  });
